### ISSUE TITLE
GBMLGG dataset

### ISSUE THREAD

**Issue by franzt7788** [lmxmercy/MGCT#1]
I have a question about how to get the GBMLGG dataset, it is a combination of GBM and LGG in TCGA? I am curious about how to get this dataset since it doesn't appear in the TCGA website.

Thank you for your help and look forward to your reply!

**Comment by lmxmercy** [comment]
Hi! I am sorry to see your question so late.
Yes, the GBMLGG dataset is a simple combination of TCGA-GBM and TCGA-LGG, you have the right idea.
If you need further help on this work, please let me know.
Mingxin

**Comment by franzt7788** [comment]
> Hi! I am sorry to see your question so late. Yes, the GBMLGG dataset is a simple combination of TCGA-GBM and TCGA-LGG, you have the right idea. If you need further help on this work, please let me know. Mingxin

Thank you for your kind reply! I tried to download, divide images into patches, and extract the feature separately for GBM and LGG. But I meet some errors in the feature extraction for GBM and LGG showing that some files cannot be found:
OSError: Unable to open file (unable to open file: name = './gbm/TCGA-06-1802-01Z-00-DX1.61b4d1f0-cb68-4da1-bf78-daafd5bf445f.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
SError: Unable to open file (unable to open file: name = './lgg/patches/TCGA-HT-7483-01Z-00-DX1.7241DF0C-1881-4366-8DD9-11BF8BDD6FBF.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

I am not sure if this is the right way to extract their feature. Do you meet this problem before or you just skip these missing files? I am really confused since I didn't meet these problems when I try to extract the feature of BLCA dataset. 

Thanks!

Best,
Franzt

**Comment by lmxmercy** [comment]
Hello Franzt! I extracted the feature embedding using the [CLAM](https://github.com/mahmoodlab/CLAM) workflow. It seems to be an error about some h5 files being missed. I can't remember whether I have encountered such a problem. You can skip the problematic WSI file first, then see if the program can run correctly. Or I can provide you with the data I used, but it may take some time to process.

**Comment by franzt7788** [comment]
> Mingxin

Hi Mingxin, thank you for your prompt reply and generous sharing. I got the point and will try to address this issue myself. The files are too large to share, I don't want to cause you any trouble. You can close this issue. Thank you again and have a nice weekend! 

Franzt

**Comment by lmxmercy** [comment]
Great! Don't hesitate to contact me if you need further help. Have a nice weekend!

**Comment by lmxmercy** [comment]
Great! Don't hesitate to contact me if you need further help. Have a nice weekend!
